version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src

    links:
      - activemq
    depends_on:
      - activemq

  activemq:
    container_name: activemq
    image: webcenter/activemq:5.14.3
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    environment:
      ACTIVEMQ_ADMIN_LOGIN: activemq
      ACTIVEMQ_ADMIN_PASSWORD: activemq
