version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    environment:
      QUEUE_URL: amqp://activemq:activemq@activemq
      TOPIC_EXAMPLE: TOPIC_EXAMPLE
    links:
      - activemq
    depends_on:
      - activemq

  activemq:
    container_name: activemq
    image: webcenter/activemq
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
      - 5671:5671
      - 5672:5672
    environment:
      ACTIVEMQ_ADMIN_LOGIN: activemq
      ACTIVEMQ_ADMIN_PASSWORD: activemq
